# Welcome {-}

```{r echo=FALSE}
.gh_url <- file.path('https://github.com', rmarkdown::metadata[['github-repo']])
```

`r rebook::openingDetails(Copyright='J. Serizay', Source=.gh_url)`

This is the landing page of the **"Orchestrating Hi-C analysis with Bioconductor"** 
book. The primary aim of this book is to introduce the `R` user to Hi-C analysis. It 
starts with key concepts important for the analysis of chromatin conformation capture and then 
presents `Bioconductor` tools that can be leveraged to process, analyse, explore and visualize 
Hi-C data. 

::: {.callout-caution}
This project is currently under active development. Several sections of this book may not be accurate, as the packages introduced in this book are still maturing. 
:::

# Introduction {-}

This book is divided in three parts:  

**Part I: Fundamentals concepts**

- [Chapter 1: What Hi-C is, experimentally and computationally](principles.qmd)
- [Chapter 2: The different `R` classes implemented to analyse Hi-C](data-representation.qmd)
- [Chapter 3: Parsing and manipulating Hi-C data in R](parsing.qmd)
- [Chapter 4: Hi-C data visualization](visualization.qmd)


**Part II: In-depth Hi-C analysis**

- [Chapter 5: Matrix-centric analysis](matrix-centric.qmd)
- [Chapter 6: Interactions-centric analysis](interactions-centric.qmd)
- [Chapter 7: Finding topological features from a Hi-C contact matrix](topological-features.qmd)


**Part III: Advanced Hi-C topics**

- [Chapter 8: Hi-C workflow: Distance-dependent interactions across yeast mutants](workflow-yeast.qmd)
- [Chapter 9: Hi-C workflow: Chromosome compartment cohesion upon mitosis entry](workflow-chicken.qmd)
- [Chapter 10: Hi-C interoperability notebook](interoperability.qmd)
